---
- name: Install package through snap
  snap: name="{{ packages }}"
  vars:
    packages: "{{ snap_packages }}"

- name: Run snap commands
  shell: "{{ item }}"
  with_items: "{{ snap_connect_cmds }}"
