---
- name: install microsoft repository
  apt: deb={{ microsoft_deb_url }}

- name: apt update
  apt:
    update_cache: yes

- name: add storage-explorer dependencies
  apt: name="{{ packages }}" state=latest update_cache=true force=yes
  vars:
    packages: "{{ storage_explorer_dependencies }}"

- name: Download storage-explorer package
  get_url: url={{ storage_explorer_url }} dest=/tmp/StorageExplorer-linux-x64.tar.gz

- name: Create storage-explorer folder
  file:
    path: /opt/storage-explorer
    state: directory
    mode: '0755'

- name: Unarchive storage-explorer
  unarchive:
    src: /tmp/StorageExplorer-linux-x64.tar.gz
    dest: /opt/storage-explorer

- name: storage-explorer permissions
  file: path="/opt/storage-explorer" owner="{{ lookup('env','USERNAME') }}" recurse="yes" state="directory"

- name: Remove downloaded tar
  file: path=/tmp/StorageExplorer-linux-x64.tar.gz state=absent

- name: Copy storage-explorer icon
  copy: src=storage-explorer.png dest=/opt/storage-explorer/icon.png

- name: add storage-explorer launcher
  copy: src=storage-explorer.desktop dest="~/.local/share/applications/storage-explorer.desktop"
  become: no
