---
- name: check if storage-explorer is installed
  stat: path=/opt/storage-explorer
  register: storage_explorer_directory

- name: Install azure explorer
  include: "azure-explorer.yml"
  when: not storage_explorer_directory.stat.exists and install_azure_explorer

- name: Check if azure cli is installed
  command: which az
  ignore_errors: yes
  register: az_cli_check

- name: Install azure cli
  include: "azure-cli.yml"
  when: az_cli_check.rc == 1