---
- name: My custom vbox to test
  hosts: customvbox
  remote_user: jobou
  become: yes

  roles:
    - apt
    - atom
    - virtualbox
    - nodejs
    - docker
    - steam
    - slack
    - skype
