---
- name: check if atom is installed
  command: dpkg-query -l atom
  register: atom_installed
  failed_when: False

- name: Download atom package
  get_url: url={{ atom_url }} dest=/tmp/atom.deb
  when: atom_installed.stdout.find('ii') == -1

- name: Install atom
  apt: deb=/tmp/atom.deb
  when: atom_installed.stdout.find('ii') == -1

- name: Remove downloaded deb
  file: path=/tmp/atom.deb state=absent
  when: atom_installed.stdout.find('ii') == -1
