---
- name: check if skype is installed
  command: dpkg-query -l skype
  register: skype_installed
  failed_when: False

- name: Download skype package
  get_url: url={{ skype_url }} dest=/tmp/skype.deb
  when: skype_installed.stdout.find('ii') == -1

- name: Install skype
  apt: deb=/tmp/skype.deb
  when: skype_installed.stdout.find('ii') == -1

- name: Remove downloaded deb
  file: path=/tmp/skype.deb state=absent
  when: skype_installed.stdout.find('ii') == -1
