---
- name: add docker apt key
  apt_key: keyserver=hkp://ha.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: add docker repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-{{ docker_ubuntu_version }} main' state=present update_cache=yes

- name: install docker
  apt: name=docker-engine

- name: create docker group
  group: name=docker state=present

- name: add docker group to user
  user: name={{ ansible_user }} groups=docker append=yes

- name: ensure docker start on boot and is running
  service: name=docker state=started enabled=yes
