---
pyenv_python_packages:
  - make
  - build-essential
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - wget
  - curl
  - llvm
  - libncurses5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
  - liblzma-dev

python_2_version: 2.7.17
python_3_version: 3.8.0

python_versions:
  - "{{ python_2_version }}"
  - 3.6.9
  - 3.7.5
  - "{{ python_3_version }}"