---
- name: check if molotov is installed
  stat: path=/usr/local/bin/molotov
  register: molotov_binary

- name: Download molotov package
  get_url: url={{ molotov_url }} dest=/usr/local/bin/molotov
  when: not molotov_binary.stat.exists

- name: make molotov.AppImage executable
  file: path=/usr/local/bin/molotov state=touch mode="a+x"
  when: not molotov_binary.stat.exists
